"""Designer/Studio handoff validation; no imagery is generated by this module."""

from .model import Invalid


def evaluate_delivery(brief, delivery):
    """Validate role-separated QC and return the design acceptance decision.

    Inputs are local JSON messages, not knowledge objects. Actual image inspection
    is performed by the named Studio/Designer reviewers, not inferred here.
    """
    required_brief = {"id", "owner", "intent", "audience", "placement", "composition", "accessibility", "acceptance_criteria"}
    if not isinstance(brief, dict) or set(brief) != required_brief or brief.get("owner") != "designer":
        raise Invalid("Brief must use the Designer-owned handoff contract")
    for key in required_brief - {"acceptance_criteria"}:
        if not isinstance(brief[key], str) or not brief[key].strip():
            raise Invalid(f"Brief needs {key}")
    criteria = brief["acceptance_criteria"]
    if not isinstance(criteria, list) or not criteria or any(not isinstance(c, str) or not c.strip() for c in criteria) or len(set(criteria)) != len(criteria):
        raise Invalid("Brief needs distinct acceptance criteria")
    required_delivery = {"brief_id", "owner", "asset_uri", "production_rationale", "rights", "image_qc", "design_fit_qc"}
    if not isinstance(delivery, dict) or set(delivery) != required_delivery or delivery.get("owner") != "studio" or delivery.get("brief_id") != brief["id"]:
        raise Invalid("Studio delivery must match the Designer brief")
    for key in ("asset_uri", "production_rationale", "rights"):
        if not isinstance(delivery[key], str) or not delivery[key].strip():
            raise Invalid(f"Delivery needs {key}")
    for field, role in (("image_qc", "studio"), ("design_fit_qc", "designer")):
        qc = delivery[field]
        if not isinstance(qc, dict) or set(qc) != {"owner", "reviewer", "status", "findings"}:
            raise Invalid(f"{field} needs a reviewer, role, result, and findings")
        if qc["owner"] != role or qc["status"] not in ("pending", "pass", "fail"):
            raise Invalid(f"{field} belongs to {role}")
        if any(not isinstance(qc[k], str) or not qc[k].strip() for k in ("reviewer", "findings")):
            raise Invalid(f"{field} needs attribution and findings")
    accepted = delivery["image_qc"]["status"] == "pass" and delivery["design_fit_qc"]["status"] == "pass"
    return {"brief_id": brief["id"], "accepted": accepted, "asset_uri": delivery["asset_uri"],
            "image_qc": delivery["image_qc"], "design_fit_qc": delivery["design_fit_qc"]}
